<a href="https://colab.research.google.com/github/Rad-01code/ML-Projects/blob/main/Python_Libraries/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

# **Section A : Array Creation**

In [5]:
# Create a 1D array of numbers from 10 to 50 (inclusive) in steps of 5.
arr1 = np.arange(10,51,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [6]:
# Create a 3x4 array of all zeros, then a 3x3 identity matrix.
arr2_1=np.zeros((3,4))
arr2_1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr2_2=np.ones((3,3))
arr2_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
# Create an array of 12 evenly spaced numbers between 0 and 1.
arr3=np.linspace(0,1,12)
arr3

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [9]:
# Create a 4x5 array of random integers between 1 and 100 and store it as arr. Use it in the next sections.
arr4 = np.random.randint(1,100,(4,5))
arr4

array([[43, 62, 59, 75, 44],
       [97, 40, 67, 42, 40],
       [ 9, 39, 42, 38, 51],
       [94, 19, 51, 18, 60]])

In [10]:
# Print the shape, dtype, number of dimensions, and size of arr4.
print(arr4.shape) #shape - (row,col) of the array
print(arr4.dtype) #dtype - data types of array elements
print(arr4.ndim) #ndim - dimension of array 1d , 2d, 3d ....nd
print(arr4.size) #size - no of elements

(4, 5)
int64
2
20


# **Section B : Indexing and slicing**

In [11]:
#Get the first row of arr4, the last column, and the element at row 2, column 3.
print(arr4[0,:])
print(arr4[:,4])
print(arr4[1,2])

[43 62 59 75 44]
[44 40 51 60]
67


In [12]:
# Get the top-left 2x2 block.
print(arr4[:2,:2])

[[43 62]
 [97 40]]


In [13]:
#Get every second column.
print(arr4[:,1])

[62 40 39 19]


In [14]:
# Reverse the order of the rows.
print(arr4[::-1,:])

[[94 19 51 18 60]
 [ 9 39 42 38 51]
 [97 40 67 42 40]
 [43 62 59 75 44]]


In [15]:
# Get all elements greater than 50 as a 1D array (boolean masking).
print(arr4[arr4>50])

[62 59 75 97 67 51 94 51 60]


In [17]:
# Replace every value below 20 with 0, working on a copy so arr stays intact. Check why .copy() matters by trying it without one.
arr4_copy=arr4.copy()
# here in numpy .copy() create an independent copy of the array
arr4_copy[arr4_copy<20]=0
arr4_copy

array([[43, 62, 59, 75, 44],
       [97, 40, 67, 42, 40],
       [ 0, 39, 42, 38, 51],
       [94,  0, 51,  0, 60]])

# **Section C: Math and aggregation**

In [22]:
# Find the mean, median, min, max, and standard deviation of arr.
print("Mean : ",np.mean(arr4))
print("Median : ",np.median(arr4))
print("Minimum value : ",np.min(arr4))
print("Maximum value : ",np.max(arr4))
print("Standard Deviation : ",np.std(arr4))


Mean :  49.5
Median :  43.5
Minimum value :  9
Maximum value :  97
Standard Deviation :  22.051077071199945


In [26]:
# Find the column-wise sum and the row-wise mean (use the axis argument).
print("Column wise sum : ",np.sum(arr4,axis=0))
print("Row wise mean : ",np.mean(arr4,axis=1))
# • axis=0 (Vertical / Downwards)
# • axis=1 (Horizontal / Across)

Column wise sum :  [243 160 219 173 195]
Row wise mean :  [56.6 57.2 35.8 48.4]


In [27]:
# Find the index of the maximum value in each row (argmax).
print("Row wise max value index : ",np.argmax(arr4,axis=1))

Row wise max value index :  [3 0 4 0]


In [29]:
# Subtract each column’s mean from that column (centering the data), using broadcasting with no loops.
col_means=np.mean(arr4,axis=0)
arr4_centered=arr4-col_means
arr4_centered

array([[-17.75,  22.  ,   4.25,  31.75,  -4.75],
       [ 36.25,   0.  ,  12.25,  -1.25,  -8.75],
       [-51.75,  -1.  , -12.75,  -5.25,   2.25],
       [ 33.25, -21.  ,  -3.75, -25.25,  11.25]])

In [31]:
# Create two arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]). Compute element-wise product, dot product, and a squared.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*b)
print(np.dot(a,b))
print(a**2)

[ 4 10 18]
32
[1 4 9]


#**Section D: Reshaping and combining**

In [34]:
# Create an array of numbers 1 to 12 and reshape it into 3x4, then 2x6, then 4x3.
arr5=np.arange(1,13)
r1= arr5.reshape(3,4)
print(r1)
r2=arr5.reshape(2,6)
print(r2)
r3=arr5.reshape(4,3)
print(r3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [36]:
# Flatten a 2D array back to 1D. (r1 -> 1d)
r1_flat=r1.flatten()
r1_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
# Stack two arrays vertically and horizontally (vstack, hstack).
a1=np.arange(1,13).reshape(3,4)
a2=np.arange(13,21).reshape(2,4)
print(np.vstack((a1,a2)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [43]:
a3=np.arange(1,13).reshape(3,4)
a4=np.arange(13,19).reshape(3,2)
print(np.hstack((a3,a4)))

[[ 1  2  3  4 13 14]
 [ 5  6  7  8 15 16]
 [ 9 10 11 12 17 18]]


In [44]:
# Transpose arr and check its new shape.
np.transpose(arr4).shape

(5, 4)

# **Section E: Mini challenges**

In [ ]:
# Ques :
# Student scores: generate a 5x4 array of random marks (0 to 100), where rows are students and columns are subjects.
# Which student has the highest total?
# Which subject has the lowest average?
# How many students scored above 80 in every subject?
# Normalize each subject’s scores to a 0-1 range (min-max scaling), since this appears again in preprocessing.

In [47]:
# ANSWER 1
scores=np.random.randint(1,100,(5,4))
scores
# rows - students , col- subjects

array([[86, 67, 29, 60],
       [97,  3, 99, 17],
       [42, 93, 51, 80],
       [39, 84, 67, 83],
       [92, 25, 73, 35]])

In [48]:
# ANSWER 2
print(np.argmax(np.sum(scores,axis=1)))

3


In [50]:
# ANSWER 3
print(np.argmin(np.average(scores,axis=0)))

1


In [51]:
# ANSWER 4
print(scores>80)

[[ True False False False]
 [ True False  True False]
 [False  True False False]
 [False  True False  True]
 [ True False False False]]


In [53]:
print((scores>80).all(axis=1))

[False False False False False]


In [54]:
print((scores>80).all(axis=1).sum())

0


In [55]:
# ANSWER 5
max_subject_score=np.max(scores,axis=0)
min_subject_score=np.min(scores,axis=0)
scores_normalized=(scores-min_subject_score)/(max_subject_score-min_subject_score)
scores_normalized

array([[0.81034483, 0.71111111, 0.        , 0.65151515],
       [1.        , 0.        , 1.        , 0.        ],
       [0.05172414, 1.        , 0.31428571, 0.95454545],
       [0.        , 0.9       , 0.54285714, 1.        ],
       [0.9137931 , 0.24444444, 0.62857143, 0.27272727]])

In [ ]:
# ques : Loop vs vectorized: create an array of 1 million random numbers. Compute the sum of squares with a Python for loop, then with NumPy only. Time both using %%time at the top of the cell.

In [63]:
arr_million=np.random.randint(1,1000000,size=1000000)

In [64]:
import time

In [65]:
start_time = time.time()
sum_of_squares=0
# Code block to measure
for i in range(arr_million.size):
  sum_of_squares+=arr_million[i]**2
end_time = time.time()
elapsed = end_time - start_time
print(elapsed)

0.7113733291625977


In [66]:
start_time = time.time()
sum_of_squares=0
# Code block to measure
np.sum(arr_million**2)
end_time = time.time()
elapsed = end_time - start_time
print(elapsed)

0.0048410892486572266
